[tool.poetry]
name = "keyboard-listener"
version = "0.3.6-rc0"
authors = [
    "Haixuan Xavier Tao <tao.xavier@outlook.com>",
    "Enzo Le Van <dev@enzo-le-van.fr>",
]
description = "Dora keyboard-listener"
license = "MIT License"
homepage = "https://github.com/dora-rs/dora.git"
documentation = "https://github.com/dora-rs/dora/blob/main/node-hub/keyboard-listener/README.md"
readme = "README.md"
packages = [{ include = "keyboard_listener" }]

[tool.poetry.dependencies]
dora-rs = "^0.3.6rc0"
numpy = "< 2.0.0"
pyarrow = ">= 5.0.0"
pynput = "^1.7.6"

[tool.poetry.scripts]
keyboard-listener = "keyboard_listener.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[project]
readme = "README.md"
